 # Site settings
baseurl = ""
languageCode = "en-us"
title = "www.VivianLark.com"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = ""

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Vivian Lark"
  description = "Author,Artist"
  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "vivianlark@outlook.com"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.jpg and overlay.png to set the background.
  backgroundpersection = true

  # hero Section
  [params.hero]
    # the picture is stored at static/images/
    type = "hero"
    title = "Vivian Lark"
    description = "Click on the links below to view the online gallery, order a copy of __The Jailer's Way__, or visit my Etsy shop to see what original pieces and prints are available."
    buttontext = "begin"

  # about section
  [[params.block]]
    id = "about"
    type = "text"
    title = "Who am I"
    description = "Hi, and thanks for visiting my website. I am an author and artist living in New York. I love to paint and draw using different mediums. From a young age I have enjoyed new projects and learning new ways of putting the beautiful things I see around me on to paper and canvas. I love making unique pieces that will put a smile on someone's face, or that will make a person stop and think about the world around them."
    buttontext = "next"
    # the picture is stored at static/images/
    picture = "Fall flower gallery shot.jpg"

  # skill section
  [[params.block]]
    id = "skills"
    type = "list"
    title = "The Jailer's Way"
    description = "At the vulnerable age of four, Theora Jailer was taught that life changes without asking for permission. Small and scared, she was taken from New York along with her two brothers to live on a coffee plantation in Tanzania, Africa, where she is raised and loved by the only person her father could trust...An aging African woman named Mahtab. Mahtab's stories, music, and smile, are a moral compass and guide for Theora over the next two decades of her life as she finds the answers to the mystery of who she is. Why was she brought to Tanzania? What are the strange symbols tattooed on her wrist? Who really were her parents? She learns through pain, fear, loss, and love, who she really is, and who she wants to be."
    buttontext = "next"
    # the picture is stored at static/images/
    picture = "New photo 2.jpg"


  # infos section
  [[params.block]]
    id = "infos"
    type = "text"
    title = "Gallery"
    description = "If you have any questions I would love to hear from you. If you would like to inquire about available pieces, feel free to contact me."
    # the picture is stored at static/images/
    picture = "New photo 1.jpeg"
  # custom section

  #[[params.block]]
   # id = "important"
    # to make custom section copy <theme>/layouts/partials/text.html to /layouts/partials/custom.html and edit it according to your needs.
   # type = "custom"
   # title = "My Artwork"
   # description = "This is a sample of the mediums I explore with."
    # the picture is stored at static/images/
   # picture = "Comp-2.jpg"

  # contact form
  [[params.block]]
    id = "contact"
    type = "contact"
    title = "Get in Touch"
    # the picture is stored at static/images/
    picture = "New photo 3.jpg"

    [params.block.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send message"

  # footer section
  # this section includes last block and social icons

  [params.footer]
    enable = true

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Instagramm"
        color = "white"
        icon = "fa-instagram"
        link = "https://www.instagram.com/vivianlarkart/"

      [[params.footer.social]]
        title = ""
        icon = ""
        link = ""

      [[params.footer.social]]
        title = "Amazon"
        icon = "fa-amazon"
        link = "https://www.amazon.com/Vivian-Lark/e/B07S8R1Z9B?ref_=dbs_p_ebk_r00_abau_000000"

      [[params.footer.social]]
        title = ""
        icon = ""
        link = ""

        [[params.footer.social]]
        title = "Etsy"
        icon = "fa-etsy"
        link = "https://www.etsy.com/shop/VivianLarkStudio"

      [[params.footer.social]]
        title = ""
        icon = ""
        link = ""

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "Â© TodrickHoho Productions"

      [[params.footer.copyright.notice]]
        text = "Design: [HTML5UP](//html5up.net)"

      [[params.footer.copyright.notice]]
text = "Demo Images: [Unsplash](//unsplash.com/)"
